name = Home Layout
description = Layout for front-page theme
template = home-layout
preview = preview.png
; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[head_right] = Head Right
regions[navigation] = Navigation
regions[slider] = Slider Area
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[panels_1] = Home Panels 1
regions[panels_2] = Home Panels 2
regions[panels_3] = Home Panels 3
regions[panels_4] = Home Panels 4
regions[content_down]  = Content Down
regions[footer_panel_1] = Footer Panel 1
regions[footer_panel_2] = Footer Panel 2


; ========================================
; Stylesheets
; ========================================

stylesheets[all][] = css/layouts/home/home.layout.styles.css
stylesheets[all][] = css/layouts/home/home.layout.no-query.css
