name = Content Layout
description = Layout for Content & news inside conexihon NewsPaper
template = content-layout
preview = preview.png
; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[head_right] = Head Right
regions[navigation] = Navigation

regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content

regions[content_down]  = Content Down
regions[footer_panel_1] = Footer Panel 1
regions[footer_panel_2] = Footer Panel 2


; ========================================
; Stylesheets
; ========================================

stylesheets[all][] = css/layouts/content/content.layout.styles.css
stylesheets[all][] = css/layouts/home/content.layout.no-query.css
